-- =========================================================
-- SUPERBASE SQL SCHEMA & RLS PROTOCOLS FOR HMS
-- Paste this entirely into your Supabase SQL Editor and run!
-- =========================================================

-- 1. Create Tables

CREATE TABLE IF NOT EXISTS patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE,
    phone TEXT,
    dob TEXT,
    registered_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    specialty TEXT,
    email TEXT UNIQUE,
    phone TEXT,
    available BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE NOT NULL,
    doctor_id BIGINT REFERENCES doctors(id) ON DELETE CASCADE NOT NULL,
    appointment_date TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'SCHEDULED', -- e.g. SCHEDULED, COMPLETED, CANCELLED
    notes TEXT
);

CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number TEXT NOT NULL UNIQUE,
    type TEXT, -- e.g. ICU, General, VIP
    status TEXT DEFAULT 'AVAILABLE', -- e.g. AVAILABLE, OCCUPIED, MAINTENANCE
    patient_id BIGINT REFERENCES patients(id) ON DELETE SET NULL
);

-- 2. Enable Row Level Security (RLS)
-- note: Your Java Spring boot application connects using the 'postgres' role
-- which automatically bypasses RLS. These policies secure the data if you 
-- ever decide to query Supabase directly from your Frontend JS.

ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies
-- Here we create simple policies. By default, APIs (anon role) are blocked.
-- Authenticated users are allowed to read data.

-- Patients Policy
CREATE POLICY "Allow authenticated read access for patients" ON patients FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert for patients" ON patients FOR INSERT TO authenticated WITH CHECK (true);

-- Doctors Policy 
-- (Public can usually see available doctors)
CREATE POLICY "Allow public read access for doctors" ON doctors FOR SELECT TO anon, authenticated USING (true);

-- Appointments Policy
CREATE POLICY "Allow authenticated read access for appointments" ON appointments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert for appointments" ON appointments FOR INSERT TO authenticated WITH CHECK (true);

-- Rooms Policy
CREATE POLICY "Allow authenticated read access for rooms" ON rooms FOR SELECT TO authenticated USING (true);

-- Note: Because your Spring Boot application is connecting via the JDBC connection
-- string and database password, it connects as the root 'postgres' user, 
-- which has BYPASSRLS privileges, granting it full read/write access regardless of these policies.
